# String Manipulation Using Pandas

In [2]:
import pandas as pd
import numpy as np
data = { 'Name': ['Lukas', 'Sofia', 'Hiroshi', 'Marta', 'Yannis', np.nan, 'Elena'],
         'City': ['Berlin', 'Madrid', 'Tokyo', 'Warsaw', 'Athens', 'Oslo', 'Lisbon'] }

In [3]:
df = pd.DataFrame(data)

In [4]:
df

      Name    City
0    Lukas  Berlin
1    Sofia  Madrid
2  Hiroshi   Tokyo
3    Marta  Warsaw
4   Yannis  Athens
5      NaN    Oslo
6    Elena  Lisbon

In [5]:
df.dtypes

Name    object
City    object
dtype: object

In [6]:
df_new = df.astype("string")

In [7]:
df_new

      Name    City
0    Lukas  Berlin
1    Sofia  Madrid
2  Hiroshi   Tokyo
3    Marta  Warsaw
4   Yannis  Athens
5     <NA>    Oslo
6    Elena  Lisbon

In [8]:
df_new.dtypes

Name    string[python]
City    string[python]
dtype: object

### .lower() :  *converts strings to lower case*

In [9]:
df_new['Name'].str.lower()

0      lukas
1      sofia
2    hiroshi
3      marta
4     yannis
5       <NA>
6      elena
Name: Name, dtype: string

### .upper() : *converts strings to upper case*

In [10]:
df_new['City'].str.upper()

0    BERLIN
1    MADRID
2     TOKYO
3    WARSAW
4    ATHENS
5      OSLO
6    LISBON
Name: City, dtype: string

### .strip() : *to remove trailing spaces*

In [11]:
df_new['Name'].str.strip()

0      Lukas
1      Sofia
2    Hiroshi
3      Marta
4     Yannis
5       <NA>
6      Elena
Name: Name, dtype: string

### .split() : *splits a string based on the character specified*

In [12]:
print(df_new['Name'].str.split("a"))

0     [Luk, s]
1     [Sofi, ]
2    [Hiroshi]
3    [M, rt, ]
4    [Y, nnis]
5         <NA>
6     [Elen, ]
Name: Name, dtype: object

### .len() : *to find the length of a string*

In [13]:
print(df_new['City'].str.len())

0    6
1    6
2    5
3    6
4    6
5    4
6    6
Name: City, dtype: Int64

### .cat() : *concatenate all strings into one*

In [14]:
print(df_new['Name'].str.cat(sep = ","))

Lukas,Sofia,Hiroshi,Marta,Yannis,Elena

### .get_dummies() : *one-hot coding for Machine learning*

In [15]:
print(df_new['City'].str.get_dummies())

   Athens  Berlin  Lisbon  Madrid  Oslo  Tokyo  Warsaw
0       0       1       0       0     0      0       0
1       0       0       0       1     0      0       0
2       0       0       0       0     0      1       0
3       0       0       0       0     0      0       1
4       1       0       0       0     0      0       0
5       0       0       0       0     1      0       0
6       0       0       1       0     0      0       0

In [16]:
print(df_new['Name'].str.get_dummies())

   Elena  Hiroshi  Lukas  Marta  Sofia  Yannis
0      0        0      1      0      0       0
1      0        0      0      0      1       0
2      0        1      0      0      0       0
3      0        0      0      1      0       0
4      0        0      0      0      0       1
5      0        0      0      0      0       0
6      1        0      0      0      0       0

### .startswith() : *finds the string that starts with a particular letter/multiple letters*

In [20]:
print(df_new['Name'].str.startswith("L","E"))

0     True
1    False
2    False
3    False
4    False
5     True
6    False
Name: Name, dtype: boolean

### .endswith() : *finds the string that ends with a particular letter/letters*

In [23]:
print(df_new['City'].str.endswith("s"))

0    False
1    False
2    False
3    False
4     True
5    False
6    False
Name: City, dtype: boolean

### .replace(old,new): *replaces a string with a new string that you specify*

In [24]:
df_new['Name'].str.replace('Lukas','El')

0         El
1      Sofia
2    Hiroshi
3      Marta
4     Yannis
5       <NA>
6      Elena
Name: Name, dtype: string

### .repeat() :*repeats the string the number of times specified*

In [25]:
df_new['City'].str.repeat(3)

0    BerlinBerlinBerlin
1    MadridMadridMadrid
2       TokyoTokyoTokyo
3    WarsawWarsawWarsaw
4    AthensAthensAthens
5          OsloOsloOslo
6    LisbonLisbonLisbon
Name: City, dtype: string

### .count(): *counts the number of times the specified character appears in the string*

In [27]:
df_new['Name'].str.count('e')

0       0
1       0
2       0
3       0
4       0
5    <NA>
6       1
Name: Name, dtype: Int64

### .findall() : *this returns the number of occurences of a specified argument*

In [30]:
print(df_new['City'].str.findall('a'))

0        []
1       [a]
2        []
3    [a, a]
4        []
5        []
6        []
Name: City, dtype: object

### .islower() :*checks if the string is lowercase, returns boolean value*

In [31]:
df_new['Name'].str.islower()

0    False
1    False
2    False
3    False
4    False
5     <NA>
6    False
Name: Name, dtype: boolean

### .isupper() :*checks if the string is uppercase, returns boolean value*

In [33]:
df_new['City'].str.isupper()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
Name: City, dtype: boolean

### .isnumeric() :*checks if the string is numeric, returns a boolean value*

In [37]:
df_new['Age'] = ["21","23","12","25","26","27","25"]

In [38]:
df_new

      Name    City Age
0    Lukas  Berlin  21
1    Sofia  Madrid  23
2  Hiroshi   Tokyo  12
3    Marta  Warsaw  25
4   Yannis  Athens  26
5     <NA>    Oslo  27
6    Elena  Lisbon  25

In [39]:
df_new['Age'].str.isnumeric()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
Name: Age, dtype: bool

### .swapcase() : *swaps lowercase to uppercase and vice-versa*

In [40]:
print(df_new['Name'].str.swapcase())

0      lUKAS
1      sOFIA
2    hIROSHI
3      mARTA
4     yANNIS
5       <NA>
6      eLENA
Name: Name, dtype: string